export const servicesData = [
  {
    id: 1,
    name: "Web Development",
    category: "IT Services",
    price: 15000,
    duration: "2 weeks",
    available: true,
    rating: 4.8,
  },
  {
    id: 2,
    name: "Digital Marketing",
    category: "Marketing",
    price: 10000,
    duration: "1 month",
    available: true,
    rating: 4.6,
  },
  {
    id: 3,
    name: "Graphic Design",
    category: "Creative",
    price: 5000,
    duration: "1 week",
    available: false,
    rating: 4.4,
  },
  {
    id: 4,
    name: "Plumbing Service",
    category: "Home Services",
    price: 1200,
    duration: "2 hours",
    available: true,
    rating: 4.3,
  },
  {
    id: 5,
    name: "House Cleaning",
    category: "Home Services",
    price: 2000,
    duration: "1 day",
    available: true,
    rating: 4.5,
  },
];
